#!/usr/bin/env ruby

require 'azure/storage'
require_relative "azure-blobstore-concourse-resource-common"

request = JSON.parse(STDIN.read)

source = request.fetch("source")
version_key = request["version"]
requested_path = version_key ? version_key["path"] : nil

@storage_account_name = source["storage_account_name"]
@storage_access_key = source["storage_access_key"]
@container = source["container"]
@environment = source["environment"]
@regexp = source["regexp"]

check_source

names_and_versions = get_names_and_versions

if requested_path.nil?
  # return latest
  puts [ {"path" => names_and_versions.last["filename"]  } ].to_json
elsif ! names_and_versions.find {|h| h["filename"] == requested_path }
  # if requested path not found, return empty array
  puts [].to_json
else
  index = names_and_versions.index {|h| h["filename"] == requested_path }
  return_list = names_and_versions[index..-1].map {|h| {"path" => h["filename"]} }
  puts return_list.to_json
end
