#!/usr/bin/env ruby

require 'azure/storage'
require 'fileutils'
require_relative 'azure-blobstore-concourse-resource-common'

request = JSON.parse(STDIN.read)

source = request.fetch("source")
requested_path = request["version"]["path"]
@storage_account_name = source["storage_account_name"]
@storage_access_key = source["storage_access_key"]
@container = source["container"]
@environment = source["environment"]
@regexp = source["regexp"]

check_source

properties = download_file(ARGV[0],requested_path)
metadata = []
properties.each_pair {|k,v| metadata << {"name"=> k.to_s, "value"=>v.to_s }  }

puts JSON.dump({ "version" => { "path" => requested_path}, "metadata" => metadata })